# Generated by Django 3.0.5 on 2020-04-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200421_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event Description and notes', null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end time and date', verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event starting time and date', verbose_name='Starting time'),
        ),
    ]
