# Generated by Django 3.0.5 on 2020-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200421_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Event Location', max_length=120, null=True, verbose_name='Event Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event Name', max_length=200, verbose_name='Event Name'),
        ),
    ]
