# Generated by Django 3.0.5 on 2020-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200421_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
